<?php

return [
    ['Wie is de officiële schrijver van de strip?',
        'Jan Kruis',
        'Marc Verhage',
        '[Correct] Willy Vandersteen',
        'Paul Geerts',
    ],
    ['Zijn Suske en Wiske broer en zus?',
        'Ze zijn halfbroer en halfzus',
        'Ze zijn stiefbroer en stiefzus',
        '[Correct] Nee',
        'Ja',
    ],
    ['Hoe heette Wiske’s pop, die oorspronkelijk een minder grote rol had in de strips?',
        'Schatje',
        'Marie',
        '[Correct] Schanulleke',
        'Dolli',
    ],
    ['Hoe reageert Lambik doorgaans als hij in de problemen komt, volgens de stereotype scènes?',
        'Hij bedenkt een rationele oplossing',
        'Hij vlucht weg en laat Suske en Wiske achter',
        '[Correct] Hij schept eerst op en belandt dan in nog meer problemen',
        'Hij schakelt meteen Jerom in',
    ],
    ['Wie is de slechterik uit de reeks die het vaakst terugkeert in de verhalen?',
        'Theofiel Boemerang',
        'Barabas',
        'Jerom',
        'De zwarte Madam',
        '[Correct] Krimson',
    ],
    ['In welk jaar verscheen het allereerste Suske en Wiske-verhaal, “Rikki en Wiske in Chocowakije”?',
        '1944',
        '[Correct] 1945',
        '1947',
        '1946',
    ],
    ['In welk deel deed Jerom zijn debuut?',
        'De vonkende vuurman',
        '[Correct] De dolle musketiers',
        'Jeromba de Griek',
        'Suskewiet',
        'Amber',
    ],
    ['In het album "De Stemmenrover" word de stem van een van de personages afgenomen. Van wie was deze stem?',
        '[Correct] Lambik',
        'Suske',
        'Sidonia',
        'Wiske',
        'Barabas',
    ],
    ['In het album "De Belhamelbende" belanden onze vrienden aan het einde van het avontuur in een Nederlands pretpark. Welk pretpark is dit?',
        'Hellendoorn',
        '[Correct] De Efteling',
        'Oranjestad',
        'Pony Park Slagharen',
        'Het land van Jan Klaasen',
    ],
    ['Lilleham is in het album "de lieve Lilleham" erg bang voor een dier. Welk dier is dit?',
        'Een paard',
        'Een witte zwaan',
        'Een zwarte kat',
        'Tobias de zwerfhond',
        '[Correct] Een zwarte ram',
    ],
    ['In het album "De Goalgetter" krijgt Suske hulp van een bepaalt iemand. Wie is dit?',
        'De vage man',
        '[Correct] De voetbalster',
        'Lambik',
        'Tante Sidonia',
        'Wiske',
    ],
    ['Onder welke naam stond Willy Vandersteen oorspronkelijk bekend in de stripwereld?',
        'Will Stein',
        'Wilmar Steen',
        'Bronzen Willy',
        '[Correct] Kaproen',
    ],
    ['Welke tekenaar nam de reeks na de periode van Willy Vandersteen voor lange tijd over?',
        'Jeff Broeckx',
        'Eric de Rop',
        '[Correct] Paul Geerts',
        'Marc Verhaegen',
    ],
    ['In welke stad speelt het avontuur van “De Ringelingschat” zich grotendeels af?',
        '[Correct] Antwerpen',
        'Brussel',
        'Mechelen',
        'Brugge',
    ],
    ['Welk personage wordt vaak omschreven als een genie op wetenschappelijk gebied en vindt regelmatig bijzondere uitvindingen uit?',
        'Theofiel Boemerang',
        'Jerom',
        'Lambik',
        '[Correct] Professor Barabas',
    ],
    ['Met welk personage trekt Suske en Wiske vaak op die eigenlijk geen familie van Suske is, maar in de loop van de strips een soort familielid van Suske wordt?',
        '[Correct] Tante Sidonia',
        'Krook',
        'Boemel',
        'Van Zwollem',
    ],
    ['Welk personage maakte zijn debuut in “Het rijmende paard” en werd later een vaste slechterik?',
        'De Zwarte Madam',
        '[Correct] Krimson',
        'Professor Rosarius',
        'Lange Soep',
    ],
    ['Waarnaar verwijst de titel “Amoras”?',
        '[Correct] Een fictief eiland',
        'Een tijdmachine-onderdeel',
        'Een anagram van ‘samora’',
        'De achternaam van Wiske',
    ],
    ['Hoe heet de serie die op Suske en Wiske is gebaseerd en uitkwam in 2013?',
        'Sooi en Sientje',
        '[Correct] Amoras Saga',
        'Rikki en Wiske',
        'De avonturen van Wiske en Schanulleke',
    ],
    ['Wie is de mol?',
        'Dennis',
        'Jan Jaap',
        'Japie',
        'Joep',
        'Johannes',
        'Marco',
        'Mart',
        'Pieter',
        '[Correct] Wols',
    ],
];
